// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiP9hJePL6NubG85eFvSdvBRBfZuQz8yw',
    appId: '1:231417173262:web:3c86003fae2507b8b0f35f',
    messagingSenderId: '231417173262',
    projectId: 'gama-physics',
    authDomain: 'gama-physics.firebaseapp.com',
    storageBucket: 'gama-physics.firebasestorage.app',
    measurementId: 'G-02VTB9HM3J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFBcKfe96hnpOHgW-w-BnWh3hlrw29s28',
    appId: '1:231417173262:android:6bd8aa68af16769fb0f35f',
    messagingSenderId: '231417173262',
    projectId: 'gama-physics',
    storageBucket: 'gama-physics.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaOLWhuKMN2V6BjJlcDGWpZ7qXTer35Mw',
    appId: '1:231417173262:ios:80fb90327eb4184eb0f35f',
    messagingSenderId: '231417173262',
    projectId: 'gama-physics',
    storageBucket: 'gama-physics.firebasestorage.app',
    iosBundleId: 'com.example.gamaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaOLWhuKMN2V6BjJlcDGWpZ7qXTer35Mw',
    appId: '1:231417173262:ios:80fb90327eb4184eb0f35f',
    messagingSenderId: '231417173262',
    projectId: 'gama-physics',
    storageBucket: 'gama-physics.firebasestorage.app',
    iosBundleId: 'com.example.gamaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiP9hJePL6NubG85eFvSdvBRBfZuQz8yw',
    appId: '1:231417173262:web:9788be8b7b8000f7b0f35f',
    messagingSenderId: '231417173262',
    projectId: 'gama-physics',
    authDomain: 'gama-physics.firebaseapp.com',
    storageBucket: 'gama-physics.firebasestorage.app',
    measurementId: 'G-8SS0GHKC92',
  );
}
